# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f203b22f8cf3dbdba5720d7053782467e93c2b7bbaa26347abb389dc88972b50553560451421d74c48ea50aa1589b66521843694c4a6a273e4c5cd781843c6ce

test:
  secret_key_base: 82e6ef576e925694682867910ef24d1c701148ce9631a9bdcdca1c35c5974aced2823ae6601133918fce806d458deebb98ac33c6c73def2f63b2b16d1c1dd654

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
